# see https://docs.docker.com/compose/compose-file/compose-versioning/
version: "3.5" # specify docker-compose version, v3.5 is compatible with docker 17.12.0+

# Define the services/containers to be run
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: coffee
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: moducoffee
    volumes:
      - ./data/mysql:/var/lib/mysql
  #     - ./mysql-initdb.d:/docker-entrypoint-initdb.d

  # no entrypoint-init scripts, see: https://github.com/Microsoft/mssql-docker/issues/11
#  mssql:
#    image: mcr.microsoft.com/mssql/server:2022-latest
#    environment:
#      - SA_PASSWORD=p@ssw0rd
#      - ACCEPT_EULA=Y
#    ports:
#      - 1433:1433
#
#  mongodb:
#    image: mongo
#    volumes:
#      - ./data/mongo:/data/db
#    ports:
#      - "27017:27017"
