DROP TABLE IF EXISTS POST;
CREATE TABLE POST (
    id INT NOT NULL AUTO_INCREMENT ,
    title VARCHAR (100) NOT NULL,
    content VARCHAR (4000) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    PRIMARY KEY (id)
)ENGINE = InnoDB COMMENT '게시물';

